// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyp2C3NcMLd4qC5iVcP-k9TyljJxnySts',
    appId: '1:3867221214:web:YOUR_WEB_APP_ID',
    messagingSenderId: '3867221214',
    projectId: 'honbab-nono',
    authDomain: 'honbab-nono.firebaseapp.com',
    storageBucket: 'honbab-nono.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyp2C3NcMLd4qC5iVcP-k9TyljJxnySts',
    appId: '1:3867221214:android:f2f597942a096b9a5e364f',
    messagingSenderId: '3867221214',
    projectId: 'honbab-nono',
    storageBucket: 'honbab-nono.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp2C3NcMLd4qC5iVcP-k9TyljJxnySts',
    appId: '1:3867221214:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '3867221214',
    projectId: 'honbab-nono',
    storageBucket: 'honbab-nono.firebasestorage.app',
    iosBundleId: 'com.honbabnono.honbabNono',
  );
}